//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDiceGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passkey
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public string PublicKey { get; set; }
        public string DeviceName { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
