//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDiceGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerReport
    {
        public int Id { get; set; }
        public int ReporterId { get; set; }
        public int ReportedId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public Nullable<int> GameId { get; set; }
        public string Reason { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> ReportDate { get; set; }
    
        public virtual GameHistory GameHistory { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
        public virtual Room Room { get; set; }
    }
}
