//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDiceGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameHistoryPlayer
    {
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public int FinalScore { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public string Status { get; set; }
    
        public virtual GameHistory GameHistory { get; set; }
        public virtual Player Player { get; set; }
    }
}
