//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDice
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class GAME_HISTORY_PLAYER
    {
        public int GameId { get; set; }
        public int PlayerId { get; set; }
        public int FinalScore { get; set; }
        public Nullable<bool> IsWinner { get; set; }
        public string Status { get; set; }
    
        public virtual PLAYER PLAYER { get; set; }
        public virtual PLAYER PLAYER1 { get; set; }
    }
}
