//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDiceGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.BackupCode = new HashSet<BackupCode>();
            this.Friendship = new HashSet<Friendship>();
            this.Friendship1 = new HashSet<Friendship>();
            this.GameHistoryPlayer = new HashSet<GameHistoryPlayer>();
            this.KickLog = new HashSet<KickLog>();
            this.KickLog1 = new HashSet<KickLog>();
            this.Passkey = new HashSet<Passkey>();
            this.PlayerReport = new HashSet<PlayerReport>();
            this.PlayerReport1 = new HashSet<PlayerReport>();
            this.PwdResetToken = new HashSet<PwdResetToken>();
            this.Room = new HashSet<Room>();
            this.RoomInvite = new HashSet<RoomInvite>();
            this.RoomInvite1 = new HashSet<RoomInvite>();
            this.RoomPlayer = new HashSet<RoomPlayer>();
            this.Scorecard = new HashSet<Scorecard>();
            this.TurnState = new HashSet<TurnState>();
            this.TwoFactorAuth = new HashSet<TwoFactorAuth>();
        }
    
        public int Id { get; set; }
        public int AvatarId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PwdHash { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> XP { get; set; }
        public Nullable<int> Level { get; set; }
        public string FriendCode { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> LastUserChange { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        public virtual Avatar Avatar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BackupCode> BackupCode { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> Friendship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Friendship> Friendship1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameHistoryPlayer> GameHistoryPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KickLog> KickLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KickLog> KickLog1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passkey> Passkey { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerReport> PlayerReport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerReport> PlayerReport1 { get; set; }
        public virtual PlayerSettings PlayerSettings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PwdResetToken> PwdResetToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomInvite> RoomInvite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomInvite> RoomInvite1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomPlayer> RoomPlayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scorecard> Scorecard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TurnState> TurnState { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TwoFactorAuth> TwoFactorAuth { get; set; }
    }
}
