//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDice
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class PLAYER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLAYER()
        {
            this.GAME_HISTORY_PLAYER = new ObservableCollection<GAME_HISTORY_PLAYER>();
            this.GAME_HISTORY_PLAYER1 = new ObservableCollection<GAME_HISTORY_PLAYER>();
        }
    
        public int Id { get; set; }
        public int AvatarId { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string PwdHash { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> XP { get; set; }
        public Nullable<int> Level { get; set; }
        public string FriendCode { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> LastUserChange { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<GAME_HISTORY_PLAYER> GAME_HISTORY_PLAYER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<GAME_HISTORY_PLAYER> GAME_HISTORY_PLAYER1 { get; set; }
    }
}
