//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDiceGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerSettings
    {
        public int PlayerId { get; set; }
        public string Title { get; set; }
        public string BgColor { get; set; }
        public string Bio { get; set; }
        public string ThemePref { get; set; }
        public string LangPref { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
