//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDiceGame.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScorecardEntry
    {
        public int ScorecardId { get; set; }
        public int CategoryId { get; set; }
        public int Points { get; set; }
        public Nullable<bool> IsUsed { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Scorecard Scorecard { get; set; }
    }
}
