//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YachtDice.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YachtDice.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string Auth_CreateAccountButton {
            get {
                return ResourceManager.GetString("Auth_CreateAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a o.
        /// </summary>
        public static string Auth_Divider {
            get {
                return ResourceManager.GetString("Auth_Divider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string Auth_Email {
            get {
                return ResourceManager.GetString("Auth_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a usuario@ejemplo.com.
        /// </summary>
        public static string Auth_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Auth_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string Auth_FirstName {
            get {
                return ResourceManager.GetString("Auth_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string Auth_ForgotPassword {
            get {
                return ResourceManager.GetString("Auth_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar como invitado.
        /// </summary>
        public static string Auth_GuestButton {
            get {
                return ResourceManager.GetString("Auth_GuestButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellidos.
        /// </summary>
        public static string Auth_LastName {
            get {
                return ResourceManager.GetString("Auth_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Auth_LoginButton {
            get {
                return ResourceManager.GetString("Auth_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string Auth_LoginTab {
            get {
                return ResourceManager.GetString("Auth_LoginTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yacht Dice.
        /// </summary>
        public static string Auth_Logo {
            get {
                return ResourceManager.GetString("Auth_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mínimo 8 caracteres.
        /// </summary>
        public static string Auth_PasswordMinPlaceholder {
            get {
                return ResourceManager.GetString("Auth_PasswordMinPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Auth_RegisterTab {
            get {
                return ResourceManager.GetString("Auth_RegisterTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El clásico juego de dados multijugador.
        /// </summary>
        public static string Auth_Subtitle {
            get {
                return ResourceManager.GetString("Auth_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Auth_Username {
            get {
                return ResourceManager.GetString("Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MiNick123.
        /// </summary>
        public static string Auth_UsernamePlaceholder {
            get {
                return ResourceManager.GetString("Auth_UsernamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Volver al inicio de sesión.
        /// </summary>
        public static string ForgotPassword_BackToLoginLink {
            get {
                return ResourceManager.GetString("ForgotPassword_BackToLoginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Te enviaremos un enlace para restablecer tu contraseña..
        /// </summary>
        public static string ForgotPassword_Description {
            get {
                return ResourceManager.GetString("ForgotPassword_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string ForgotPassword_Email {
            get {
                return ResourceManager.GetString("ForgotPassword_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar enlace de recuperación.
        /// </summary>
        public static string ForgotPassword_SendLinkButton {
            get {
                return ResourceManager.GetString("ForgotPassword_SendLinkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recuperar contraseña.
        /// </summary>
        public static string ForgotPassword_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bono +35.
        /// </summary>
        public static string Game_CategoryBonus {
            get {
                return ResourceManager.GetString("Game_CategoryBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chance.
        /// </summary>
        public static string Game_CategoryChance {
            get {
                return ResourceManager.GetString("Game_CategoryChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cincos.
        /// </summary>
        public static string Game_CategoryFives {
            get {
                return ResourceManager.GetString("Game_CategoryFives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 4 Iguales.
        /// </summary>
        public static string Game_CategoryFourOfAKind {
            get {
                return ResourceManager.GetString("Game_CategoryFourOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuatros.
        /// </summary>
        public static string Game_CategoryFours {
            get {
                return ResourceManager.GetString("Game_CategoryFours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Casa llena.
        /// </summary>
        public static string Game_CategoryFullHouse {
            get {
                return ResourceManager.GetString("Game_CategoryFullHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esc. Grande.
        /// </summary>
        public static string Game_CategoryLargeStraight {
            get {
                return ResourceManager.GetString("Game_CategoryLargeStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unos.
        /// </summary>
        public static string Game_CategoryOnes {
            get {
                return ResourceManager.GetString("Game_CategoryOnes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seises.
        /// </summary>
        public static string Game_CategorySixes {
            get {
                return ResourceManager.GetString("Game_CategorySixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esc. Pequeña.
        /// </summary>
        public static string Game_CategorySmallStraight {
            get {
                return ResourceManager.GetString("Game_CategorySmallStraight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Suma.
        /// </summary>
        public static string Game_CategorySum {
            get {
                return ResourceManager.GetString("Game_CategorySum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 3 Iguales.
        /// </summary>
        public static string Game_CategoryThreeOfAKind {
            get {
                return ResourceManager.GetString("Game_CategoryThreeOfAKind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tres.
        /// </summary>
        public static string Game_CategoryThrees {
            get {
                return ResourceManager.GetString("Game_CategoryThrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dos.
        /// </summary>
        public static string Game_CategoryTwos {
            get {
                return ResourceManager.GetString("Game_CategoryTwos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a YACHT.
        /// </summary>
        public static string Game_CategoryYacht {
            get {
                return ResourceManager.GetString("Game_CategoryYacht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cómo jugar.
        /// </summary>
        public static string Game_HowToPlayButton {
            get {
                return ResourceManager.GetString("Game_HowToPlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar jugador.
        /// </summary>
        public static string Game_KickPlayerButton {
            get {
                return ResourceManager.GetString("Game_KickPlayerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salir de la partida.
        /// </summary>
        public static string Game_LeaveMatchButton {
            get {
                return ResourceManager.GetString("Game_LeaveMatchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Game_PlayersHeader {
            get {
                return ResourceManager.GetString("Game_PlayersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Turno de {0}.
        /// </summary>
        public static string Game_PlayerTurnText {
            get {
                return ResourceManager.GetString("Game_PlayerTurnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Presiona Tirar para comenzar.
        /// </summary>
        public static string Game_PressRollHint {
            get {
                return ResourceManager.GetString("Game_PressRollHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tirar ({0}/3).
        /// </summary>
        public static string Game_RollButton {
            get {
                return ResourceManager.GetString("Game_RollButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda {0} / {1}.
        /// </summary>
        public static string Game_RoundInfo {
            get {
                return ResourceManager.GetString("Game_RoundInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ronda {0} / {1}.
        /// </summary>
        public static string Game_RoundInfoText {
            get {
                return ResourceManager.GetString("Game_RoundInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tabla de puntaje.
        /// </summary>
        public static string Game_ScorecardTitle {
            get {
                return ResourceManager.GetString("Game_ScorecardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOTAL.
        /// </summary>
        public static string Game_TotalLabel {
            get {
                return ResourceManager.GetString("Game_TotalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu turno.
        /// </summary>
        public static string Game_YourTurnText {
            get {
                return ResourceManager.GetString("Game_YourTurnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Volver a Jugar.
        /// </summary>
        public static string Leaderboard_BackLink {
            get {
                return ResourceManager.GetString("Leaderboard_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nivel.
        /// </summary>
        public static string Leaderboard_ColumnLevel {
            get {
                return ResourceManager.GetString("Leaderboard_ColumnLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string Leaderboard_ColumnPlayer {
            get {
                return ResourceManager.GetString("Leaderboard_ColumnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string Leaderboard_ColumnPoints {
            get {
                return ResourceManager.GetString("Leaderboard_ColumnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a #.
        /// </summary>
        public static string Leaderboard_ColumnRank {
            get {
                return ResourceManager.GetString("Leaderboard_ColumnRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victorias.
        /// </summary>
        public static string Leaderboard_ColumnWins {
            get {
                return ResourceManager.GetString("Leaderboard_ColumnWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string Leaderboard_FilterFriends {
            get {
                return ResourceManager.GetString("Leaderboard_FilterFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Global.
        /// </summary>
        public static string Leaderboard_FilterGlobal {
            get {
                return ResourceManager.GetString("Leaderboard_FilterGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador Global.
        /// </summary>
        public static string Leaderboard_Title {
            get {
                return ResourceManager.GetString("Leaderboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu posición: #{0}.
        /// </summary>
        public static string Leaderboard_YourPosition {
            get {
                return ResourceManager.GetString("Leaderboard_YourPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Volver a Jugar.
        /// </summary>
        public static string Lobby_BackToPlayLink {
            get {
                return ResourceManager.GetString("Lobby_BackToPlayLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copiar código.
        /// </summary>
        public static string Lobby_CopyCodeButton {
            get {
                return ResourceManager.GetString("Lobby_CopyCodeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modo de juego.
        /// </summary>
        public static string Lobby_GameMode {
            get {
                return ResourceManager.GetString("Lobby_GameMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Anfitrión.
        /// </summary>
        public static string Lobby_HostTag {
            get {
                return ResourceManager.GetString("Lobby_HostTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Máx. jugadores.
        /// </summary>
        public static string Lobby_MaxPlayers {
            get {
                return ResourceManager.GetString("Lobby_MaxPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ritmo normal · Sin presión.
        /// </summary>
        public static string Lobby_Mode1MinSubtitle {
            get {
                return ResourceManager.GetString("Lobby_Mode1MinSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1 minuto.
        /// </summary>
        public static string Lobby_Mode1MinTitle {
            get {
                return ResourceManager.GetString("Lobby_Mode1MinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ritmo rápido · Bajo presión.
        /// </summary>
        public static string Lobby_Mode30sSubtitle {
            get {
                return ResourceManager.GetString("Lobby_Mode30sSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 30 segundos.
        /// </summary>
        public static string Lobby_Mode30sTitle {
            get {
                return ResourceManager.GetString("Lobby_Mode30sTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores.
        /// </summary>
        public static string Lobby_Players {
            get {
                return ResourceManager.GetString("Lobby_Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacidad.
        /// </summary>
        public static string Lobby_Privacy {
            get {
                return ResourceManager.GetString("Lobby_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privado.
        /// </summary>
        public static string Lobby_PrivateOption {
            get {
                return ResourceManager.GetString("Lobby_PrivateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Público.
        /// </summary>
        public static string Lobby_PublicOption {
            get {
                return ResourceManager.GetString("Lobby_PublicOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida →.
        /// </summary>
        public static string Lobby_StartGameButton {
            get {
                return ResourceManager.GetString("Lobby_StartGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string Lobby_Title {
            get {
                return ResourceManager.GetString("Lobby_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esperando jugador....
        /// </summary>
        public static string Lobby_WaitingForPlayerText {
            get {
                return ResourceManager.GetString("Lobby_WaitingForPlayerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string MainMenu_EditProfileButton {
            get {
                return ResourceManager.GetString("MainMenu_EditProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a + Agregar.
        /// </summary>
        public static string MainMenu_Friends_AddButton {
            get {
                return ResourceManager.GetString("MainMenu_Friends_AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EN PARTIDA.
        /// </summary>
        public static string MainMenu_Friends_InMatchHeader {
            get {
                return ResourceManager.GetString("MainMenu_Friends_InMatchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} en línea.
        /// </summary>
        public static string MainMenu_Friends_OnlineCount {
            get {
                return ResourceManager.GetString("MainMenu_Friends_OnlineCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EN LÍNEA.
        /// </summary>
        public static string MainMenu_Friends_OnlineHeader {
            get {
                return ResourceManager.GetString("MainMenu_Friends_OnlineHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a en línea.
        /// </summary>
        public static string MainMenu_Friends_OnlineSuffix {
            get {
                return ResourceManager.GetString("MainMenu_Friends_OnlineSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SOLICITUDES.
        /// </summary>
        public static string MainMenu_Friends_RequestsHeader {
            get {
                return ResourceManager.GetString("MainMenu_Friends_RequestsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar usuario....
        /// </summary>
        public static string MainMenu_Friends_SearchPlaceholder {
            get {
                return ResourceManager.GetString("MainMenu_Friends_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En partida - Lobby.
        /// </summary>
        public static string MainMenu_Friends_StatusInLobby {
            get {
                return ResourceManager.GetString("MainMenu_Friends_StatusInLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En partida - Ronda {0}.
        /// </summary>
        public static string MainMenu_Friends_StatusInMatchRound {
            get {
                return ResourceManager.GetString("MainMenu_Friends_StatusInMatchRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En línea.
        /// </summary>
        public static string MainMenu_Friends_StatusOnline {
            get {
                return ResourceManager.GetString("MainMenu_Friends_StatusOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lista de jugadores.
        /// </summary>
        public static string MainMenu_Friends_Subtitle {
            get {
                return ResourceManager.GetString("MainMenu_Friends_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigos.
        /// </summary>
        public static string MainMenu_Friends_Title {
            get {
                return ResourceManager.GetString("MainMenu_Friends_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quiere ser tu amigo.
        /// </summary>
        public static string MainMenu_Friends_WantsToBeFriend {
            get {
                return ResourceManager.GetString("MainMenu_Friends_WantsToBeFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string MainMenu_LogoutButton {
            get {
                return ResourceManager.GetString("MainMenu_LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marcador.
        /// </summary>
        public static string MainMenu_Nav_Leaderboard {
            get {
                return ResourceManager.GetString("MainMenu_Nav_Leaderboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala de espera.
        /// </summary>
        public static string MainMenu_Nav_Lobby {
            get {
                return ResourceManager.GetString("MainMenu_Nav_Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugar.
        /// </summary>
        public static string MainMenu_Nav_Play {
            get {
                return ResourceManager.GetString("MainMenu_Nav_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string MainMenu_Nav_Settings {
            get {
                return ResourceManager.GetString("MainMenu_Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea una partida privada y espera a tus amigos.
        /// </summary>
        public static string MainMenu_Play_CreateRoomDescription {
            get {
                return ResourceManager.GetString("MainMenu_Play_CreateRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear sala.
        /// </summary>
        public static string MainMenu_Play_CreateRoomTitle {
            get {
                return ResourceManager.GetString("MainMenu_Play_CreateRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar →.
        /// </summary>
        public static string MainMenu_Play_JoinButton {
            get {
                return ResourceManager.GetString("MainMenu_Play_JoinButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de una sala.
        /// </summary>
        public static string MainMenu_Play_JoinRoomDescription {
            get {
                return ResourceManager.GetString("MainMenu_Play_JoinRoomDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string MainMenu_Play_JoinRoomTitle {
            get {
                return ResourceManager.GetString("MainMenu_Play_JoinRoomTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niv {0}.
        /// </summary>
        public static string MainMenu_Play_LevelBadge {
            get {
                return ResourceManager.GetString("MainMenu_Play_LevelBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor puntaje.
        /// </summary>
        public static string MainMenu_Play_StatBestScore {
            get {
                return ResourceManager.GetString("MainMenu_Play_StatBestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas.
        /// </summary>
        public static string MainMenu_Play_StatGames {
            get {
                return ResourceManager.GetString("MainMenu_Play_StatGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a % Victoria.
        /// </summary>
        public static string MainMenu_Play_StatWinRate {
            get {
                return ResourceManager.GetString("MainMenu_Play_StatWinRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victorias.
        /// </summary>
        public static string MainMenu_Play_StatWins {
            get {
                return ResourceManager.GetString("MainMenu_Play_StatWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de vuelta,.
        /// </summary>
        public static string MainMenu_Play_WelcomeText {
            get {
                return ResourceManager.GetString("MainMenu_Play_WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Niv {0}.
        /// </summary>
        public static string MainMenu_PlayerLevel {
            get {
                return ResourceManager.GetString("MainMenu_PlayerLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logros.
        /// </summary>
        public static string Profile_AchievementsHeader {
            get {
                return ResourceManager.GetString("Profile_AchievementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Volver.
        /// </summary>
        public static string Profile_BackButton {
            get {
                return ResourceManager.GetString("Profile_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color de fondo.
        /// </summary>
        public static string Profile_BackgroundColor {
            get {
                return ResourceManager.GetString("Profile_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tirador veloz.
        /// </summary>
        public static string Profile_BadgeFastRoller {
            get {
                return ResourceManager.GetString("Profile_BadgeFastRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera partida.
        /// </summary>
        public static string Profile_BadgeFirstMatch {
            get {
                return ResourceManager.GetString("Profile_BadgeFirstMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primera victoria.
        /// </summary>
        public static string Profile_BadgeFirstWin {
            get {
                return ResourceManager.GetString("Profile_BadgeFirstWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Elige tu avatar.
        /// </summary>
        public static string Profile_ChooseAvatar {
            get {
                return ResourceManager.GetString("Profile_ChooseAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalizar perfil.
        /// </summary>
        public static string Profile_CustomizeProfileTitle {
            get {
                return ResourceManager.GetString("Profile_CustomizeProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar cambios.
        /// </summary>
        public static string Profile_SaveChangesButton {
            get {
                return ResourceManager.GetString("Profile_SaveChangesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mejor puntaje.
        /// </summary>
        public static string Profile_StatBestScore {
            get {
                return ResourceManager.GetString("Profile_StatBestScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Partidas.
        /// </summary>
        public static string Profile_StatGames {
            get {
                return ResourceManager.GetString("Profile_StatGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estadísticas.
        /// </summary>
        public static string Profile_StatisticsHeader {
            get {
                return ResourceManager.GetString("Profile_StatisticsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victorias.
        /// </summary>
        public static string Profile_StatWins {
            get {
                return ResourceManager.GetString("Profile_StatWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debutante.
        /// </summary>
        public static string Profile_TitleBeginner {
            get {
                return ResourceManager.GetString("Profile_TitleBeginner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Experto en dados.
        /// </summary>
        public static string Profile_TitleDiceExpert {
            get {
                return ResourceManager.GetString("Profile_TitleDiceExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tirador veloz.
        /// </summary>
        public static string Profile_TitleFastRoller {
            get {
                return ResourceManager.GetString("Profile_TitleFastRoller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Título.
        /// </summary>
        public static string Profile_TitleLabel {
            get {
                return ResourceManager.GetString("Profile_TitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estratega.
        /// </summary>
        public static string Profile_TitleStrategist {
            get {
                return ResourceManager.GetString("Profile_TitleStrategist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campeón del Yacht.
        /// </summary>
        public static string Profile_TitleYachtChampion {
            get {
                return ResourceManager.GetString("Profile_TitleYachtChampion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XP total.
        /// </summary>
        public static string Profile_TotalXp {
            get {
                return ResourceManager.GetString("Profile_TotalXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Profile_Username {
            get {
                return ResourceManager.GetString("Profile_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string Results_ColumnPlayer {
            get {
                return ResourceManager.GetString("Results_ColumnPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Total.
        /// </summary>
        public static string Results_ColumnTotal {
            get {
                return ResourceManager.GetString("Results_ColumnTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a XP ganada.
        /// </summary>
        public static string Results_ColumnXp {
            get {
                return ResourceManager.GetString("Results_ColumnXp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string Results_MenuButton {
            get {
                return ResourceManager.GetString("Results_MenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva partida.
        /// </summary>
        public static string Results_NewGameButton {
            get {
                return ResourceManager.GetString("Results_NewGameButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje ganador: {0} pts.
        /// </summary>
        public static string Results_ScoreSubtitle {
            get {
                return ResourceManager.GetString("Results_ScoreSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} ganó.
        /// </summary>
        public static string Results_WinnerTitle {
            get {
                return ResourceManager.GetString("Results_WinnerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Avatar y personalización.
        /// </summary>
        public static string Settings_Account_Avatar {
            get {
                return ResourceManager.GetString("Settings_Account_Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string Settings_Account_ChangeButton {
            get {
                return ResourceManager.GetString("Settings_Account_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar perfil.
        /// </summary>
        public static string Settings_Account_EditProfileButton {
            get {
                return ResourceManager.GetString("Settings_Account_EditProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string Settings_Account_Email {
            get {
                return ResourceManager.GetString("Settings_Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string Settings_Account_Username {
            get {
                return ResourceManager.GetString("Settings_Account_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tema oscuro.
        /// </summary>
        public static string Settings_Appearance_DarkTheme {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambia la apariencia de toda la interfaz.
        /// </summary>
        public static string Settings_Appearance_DarkThemeSubtitle {
            get {
                return ResourceManager.GetString("Settings_Appearance_DarkThemeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Volver a Jugar.
        /// </summary>
        public static string Settings_BackLink {
            get {
                return ResourceManager.GetString("Settings_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mi cuenta.
        /// </summary>
        public static string Settings_NavAccount {
            get {
                return ResourceManager.GetString("Settings_NavAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apariencia.
        /// </summary>
        public static string Settings_NavAppearance {
            get {
                return ResourceManager.GetString("Settings_NavAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones.
        /// </summary>
        public static string Settings_NavNotifications {
            get {
                return ResourceManager.GetString("Settings_NavNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias.
        /// </summary>
        public static string Settings_NavPreferences {
            get {
                return ResourceManager.GetString("Settings_NavPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Privacidad.
        /// </summary>
        public static string Settings_NavPrivacy {
            get {
                return ResourceManager.GetString("Settings_NavPrivacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seguridad.
        /// </summary>
        public static string Settings_NavSecurity {
            get {
                return ResourceManager.GetString("Settings_NavSecurity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Notificaciones de partida.
        /// </summary>
        public static string Settings_Notifications_Match {
            get {
                return ResourceManager.GetString("Settings_Notifications_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cuando te inviten a jugar.
        /// </summary>
        public static string Settings_Notifications_MatchSubtitle {
            get {
                return ResourceManager.GetString("Settings_Notifications_MatchSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sonidos del juego.
        /// </summary>
        public static string Settings_Notifications_Sounds {
            get {
                return ResourceManager.GetString("Settings_Notifications_Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Efectos al tirar dados.
        /// </summary>
        public static string Settings_Notifications_SoundsSubtitle {
            get {
                return ResourceManager.GetString("Settings_Notifications_SoundsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Settings_Preferences_Language {
            get {
                return ResourceManager.GetString("Settings_Preferences_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mostrar puntos potenciales.
        /// </summary>
        public static string Settings_Preferences_ShowPotentialPoints {
            get {
                return ResourceManager.GetString("Settings_Preferences_ShowPotentialPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ver puntos antes de anotar.
        /// </summary>
        public static string Settings_Preferences_ShowPotentialPointsSubtitle {
            get {
                return ResourceManager.GetString("Settings_Preferences_ShowPotentialPointsSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar cuenta.
        /// </summary>
        public static string Settings_Privacy_DeleteAccountButton {
            get {
                return ResourceManager.GetString("Settings_Privacy_DeleteAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil público.
        /// </summary>
        public static string Settings_Privacy_PublicProfile {
            get {
                return ResourceManager.GetString("Settings_Privacy_PublicProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otros jugadores pueden ver tu perfil.
        /// </summary>
        public static string Settings_Privacy_PublicProfileSubtitle {
            get {
                return ResourceManager.GetString("Settings_Privacy_PublicProfileSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string Settings_Security_ChangeButton {
            get {
                return ResourceManager.GetString("Settings_Security_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Settings_Security_Password {
            get {
                return ResourceManager.GetString("Settings_Security_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación en 2 pasos.
        /// </summary>
        public static string Settings_Security_TwoFactor {
            get {
                return ResourceManager.GetString("Settings_Security_TwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de correo al iniciar sesión.
        /// </summary>
        public static string Settings_Security_TwoFactorSubtitle {
            get {
                return ResourceManager.GetString("Settings_Security_TwoFactorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ajustes.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ← Volver.
        /// </summary>
        public static string TwoFactor_BackLink {
            get {
                return ResourceManager.GetString("TwoFactor_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reenviar.
        /// </summary>
        public static string TwoFactor_ResendLink {
            get {
                return ResourceManager.GetString("TwoFactor_ResendLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No llegó el código?.
        /// </summary>
        public static string TwoFactor_ResendText {
            get {
                return ResourceManager.GetString("TwoFactor_ResendText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el código de 6 dígitos enviado a.
        /// </summary>
        public static string TwoFactor_Subtitle {
            get {
                return ResourceManager.GetString("TwoFactor_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificación en dos pasos.
        /// </summary>
        public static string TwoFactor_Title {
            get {
                return ResourceManager.GetString("TwoFactor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verificar →.
        /// </summary>
        public static string TwoFactor_VerifyButton {
            get {
                return ResourceManager.GetString("TwoFactor_VerifyButton", resourceCulture);
            }
        }
    }
}
